### ISSUE TITLE
0.81 release date?

### ISSUE THREAD

**Issue by jeteve** [rustyconover/net-amazon-s3#6]
Hi, sorry it might not be the right place to ask for this, but it looks like I would need the 0.81 release, as it contains multi-region support (which I need)

Any estimated date for the 0.81 release?

**Comment by rustyconover** [comment]
Hi Jerome,

No real date set yet.  Are you trying to talk to the eu-central-1 region?  Because that isn’t going to work yet.

Rusty
-- 
Rusty Conover
Lucky Dinosaur, LLC.

On July 1, 2015 at 1:25:15 PM, Jerome Eteve (notifications@github.com) wrote:

Hi, sorry it might not be the right place to ask for this, but it looks like I would need the 0.81 release, as it contains multi-region support (which I need)

Any estimated date for the 0.81 release?

**Comment by shotarok** [comment]
Hi @rustyconover,

I'd like to use `use_virtual_host` feature, which v0.80 does not include. Could you upload the current master (795297a) to CPAN as v0.81?

Thanks,
Shotaro

**Comment by Etsukata** [comment]
> Are you trying to talk to the eu-central-1 region?

* Even with 0.80(not yet has `user_virtual_host`) , it's possible to access the eu-central-1 region by passing `host` parameter on `Net::Amazon::S3->new` like,
```perl
    my $s3 = Net::Amazon::S3->new(
        {
            aws_access_key_id     => $self->aws_access_key_id,
            aws_secret_access_key => $self->aws_secret_access_key,
            host                  => 's3.eu-central-1.amazonaws.com',
        }
    );
```
* but obviously v0.81(with `user_virtual_host`) will be prefered.

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL released please test and open ticket if there are any issues released
